apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-web
  namespace: qaq-dev
  labels:
    app: template-web
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-web
      version: v1
  template:
    metadata:
      labels:
        app: template-web
        version: v1
    spec:
      imagePullSecrets:
        - name: harborsecret
      containers:
        - name: template-web
          image: blacklee123/template-web:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: template-web-conf
              mountPath: /etc/nginx/conf.d/
      volumes:
      - name: template-web-conf
        configMap:
          name: template-web-conf
